resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: src
  type: pull-request
  source:
    repository: ((github-repository))
    access_token: ((github-token))
    ignore_paths:
    - thirdeye-ui

- name: ui-src
  type: pull-request
  source:
    repository: ((github-repository))
    access_token: ((github-token))
    paths:
    - pom.xml
    - thirdeye-ui

jobs:
- name: build-server-pr
  plan:
  - get: src
    trigger: true
    version: every
  - put: src
    params:
      path: src
      status: pending
  - task: build-pr
    file: src/.concourse/tasks/build-thirdeye/build-thirdeye.yml
    input_mapping:
      ci-src: src
  - put: src
    params:
      path: src
      status: success
  on_failure:
    do:
    - put: src
      params:
        path: src
        status: failure
    - put: slack
      params:
        channel: ((slack-channel))
        text: |
          <!channel> Failed to build PR for Thirdeye Server
          ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  on_success:
    put: slack
    params:
      channel: ((slack-channel))
      text: |
        PR for Thirdeye Server been successfully built.
        ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: build-ui-pr
  plan:
  - get: ui-src
    trigger: true
    version: every
  - put: ui-src
    params:
      path: ui-src
      status: pending
  - task: build-pr
    file: ui-src/.concourse/tasks/build-thirdeye/build-thirdeye.yml
    input_mapping:
      ci-src: ui-src
  - put: ui-src
    params:
      path: ui-src
      status: success
  on_failure:
    do:
    - put: ui-src
      params:
        path: src
        status: failure
    - put: slack
      params:
        channel: ((slack-channel))
        text: |
          <!channel> Failed to build PR for Thirdeye UI
          ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  on_success:
    put: slack
    params:
      channel: ((slack-channel))
      text: |
        PR for Thirdeye UI been successfully built.
        ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME