######################################################
# ThirdEye Coordinator default config
######################################################

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin

  connector:
    type: http
    port: 8080
    idleTimeout: 620s
#   SSL connector is disabled since APP Engine only allows exposing a single port.
#   A sample keystore and password is added so that this can be tested locally.
#   However, the settings currently don't work on GAE
#    - type: https
#      port: 8443
#      keyStorePath: conf/keystore.jks
#      keyStorePassword: password

logging:
  level: INFO
  loggers:
    org.apache.pinot.thirdeye: DEBUG
    org.apache.zookeeper: WARN

auth:
  enabled: false
  jwt:
    signingKey: 9sz834jghfdglsE4sYNT4zfrU4JwLARcUhxd2
    issuer: thirdeye
    accessTokenExpiry: P1D # Duration: 1 day. Format: https://en.wikipedia.org/wiki/ISO_8601

database:
  # Assuming a local MySQL server running on the default port 3306
  url: jdbc:mysql://localhost/thirdeye_test?autoReconnect=true&useSSL=false
  user: uthirdeye
  password: pass
  driver: com.mysql.jdbc.Driver

swagger:
  # Enable/Disable the swagger resource. Helps in API documentation. Should be true by default
  enabled: true

  # package to scan for jersey resources
  resourcePackage: org.apache.pinot.thirdeye.resources

# Start the Task Driver. This module runs the detection and notification tasks
taskDriver:
  enabled: true
  id: 0 # must be a non-negative integer unique per instance/worker

# Run the Quartz Scheduler.
# Only 1 instance of scheduler should run. This responsibility is currently on the user!!
schedulerEnabled: true

mockEvents:
  enabled: true
  generators:
    - type: HOLIDAY
      arrivalType: exponential
      arrivalMean: 86400000
      durationType: fixed
      durationMean: 86400000
      seed: 0
      namePrefixes: [First, Second, Third, Last, Funky, Happy, Sad, Glorious, Jolly, Unity, Pinot's]
      nameSuffixes: [day, day, days, celebration, rememberance, occurrence, moment]
    - type: INFORMED
      arrivalType: exponential
      arrivalMean: 43200000
      durationType: exponential
      durationMean: 3600000
      seed: 1
      namePrefixes: [Login, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
      nameSuffixes: [backend, frontend, v1.1, v1.2, v1.3, v2.0, v3, v4, v5, storage, topic, container, database]
    - type: CM
      arrivalType: exponential
      arrivalMean: 21600000
      durationType: fixed
      durationMean: 1800000
      seed: 2
      namePrefixes: [Database, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
    - type: CUSTOM
      arrivalType: exponential
      arrivalMean: 432000000
      durationType: exponential
      durationMean: 86400000
      seed: 3
      namePrefixes: [Marketing, Onboarding, Vaction, Outreach, InDay]
      nameSuffixes: [integration, campaign, meeting]
    - type: LIX
      arrivalType: exponential
      arrivalMean: 259200000
      durationType: exponential
      durationMean: 604800000
      seed: 4
      namePrefixes: [System, Model, Campaign, Welcome, Pinot, ThirdEye]
      nameSuffixes: [tuning, bugfix, rollout, test]

dashboardHost: "http://localhost:8081"
alerterConfigurations:
  smtpConfiguration:
    smtpHost: localhost
    smtpPort: 25
    smtpUser: no-reply@thirdeye.startree.ai
    smtpPassword: my-password
#  jiraConfiguration:
#    jiraUser: <REPLACE_ME>
#    jiraPassword: <REPLACE_ME>
#    jiraUrl: <REPLACE_ME>
#    jiraDefaultProject: <REPLACE_ME>
#    jiraIssueTypeId: 19
failureFromAddress: "thirdeye@localhost"
failureToAddress: "thirdeye@localhost"
phantomJsPath: "/usr/local/bin/jstf"
