######################################################
# ThirdEye Worker default config
######################################################

server:
  type: default
  rootPath: '/api/*'
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 1867
  adminConnectors:
    - type: http
      port: 1868


alert: true

# Enable autoloading data sources with a default frequency of 5 min
autoload: true
autoOnboardConfiguration:
  frequency: PT5m # 5 min

mockEventsLoader: true
monitor: false
pinotProxy: false
scheduler: true
worker: true
detectionPipeline: true
detectionAlert: true
dashboardHost: "http://localhost:1426"
id: 0
alerterConfiguration:
  smtpConfiguration:
    smtpHost: "localhost"
    smtpPort: 25
#  jiraConfiguration:
#    jiraUser: <REPLACE_ME>
#    jiraPassword: <REPLACE_ME>
#    jiraUrl: <REPLACE_ME>
#    jiraDefaultProject: <REPLACE_ME>
#    jiraIssueTypeId: 19
failureFromAddress: "thirdeye@localhost"
failureToAddress: "thirdeye@localhost"
phantomJsPath: "/usr/local/bin/jstf"

swagger:
  resourcePackage: org.apache.pinot.thirdeye.dashboard.resources,org.apache.pinot.thirdeye.dashboard.resources.v2,org.apache.pinot.thirdeye.anomaly.onboard

logging:
  level: INFO
  loggers:
    org.apache.pinot.thirdeye: DEBUG
    org.apache.zookeeper: WARN

mockEventsLoaderConfiguration:
  generators:
    - type: HOLIDAY
      arrivalType: exponential
      arrivalMean: 86400000
      durationType: fixed
      durationMean: 86400000
      seed: 0
      namePrefixes: [First, Second, Third, Last, Funky, Happy, Sad, Glorious, Jolly, Unity, Pinot's]
      nameSuffixes: [day, day, days, celebration, rememberance, occurrence, moment]
    - type: INFORMED
      arrivalType: exponential
      arrivalMean: 43200000
      durationType: exponential
      durationMean: 3600000
      seed: 1
      namePrefixes: [Login, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
      nameSuffixes: [backend, frontend, v1.1, v1.2, v1.3, v2.0, v3, v4, v5, storage, topic, container, database]
    - type: CM
      arrivalType: exponential
      arrivalMean: 21600000
      durationType: fixed
      durationMean: 1800000
      seed: 2
      namePrefixes: [Database, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
    - type: CUSTOM
      arrivalType: exponential
      arrivalMean: 432000000
      durationType: exponential
      durationMean: 86400000
      seed: 3
      namePrefixes: [Marketing, Onboarding, Vaction, Outreach, InDay]
      nameSuffixes: [integration, campaign, meeting]
    - type: LIX
      arrivalType: exponential
      arrivalMean: 259200000
      durationType: exponential
      durationMean: 604800000
      seed: 4
      namePrefixes: [System, Model, Campaign, Welcome, Pinot, ThirdEye]
      nameSuffixes: [tuning, bugfix, rollout, test]
