---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: daniellavoie/ci-java-8
    tag: latest

inputs:
- name: ci-src
- name: src

outputs:
- name: src
- name: version

params:
  MVN_REPOSITORY_USERNAME: ((artifactory-username))
  MVN_REPOSITORY_PASSWORD: ((artifactory-password))

run:
  path: ci-src/.concourse/tasks/build-thirdeye/build-thirdeye.sh
