---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.3-adoptopenjdk-8

inputs:
- name: ci-src
- name: src

outputs:
- name: version

caches:
- path: src/m2

run:
  path: ci-src/.concourse/tasks/extract-maven-version/extract-maven-version.sh