name: "Intraday Style Revenue Report Ads"
collection: sample

tables:
  - metric: cost
    baselineSize: 7
    baselineUnit: DAYS

schedules:
  "1 HOURLY SCHEDULE":
    cron: "1 * * * * ?"
    aggregationSize: 1
    aggregationUnit: HOURS
    reportWindow: 24
    lagSize: 2
    lagUnit: HOURS
    emailTo: "npawar@linkedin.com"
    emailFrom: "npawar@linkedin.com"
    nameTo: "Reports Mailing List"
    nameFrom: "Thirdeye Reporting"