name: Release ThirdEye UI

on:
  # a release must be triggered manually
  workflow_dispatch:

jobs:
  release-thirdeye-ui:
    runs-on: ubuntu-latest
    environment: github-production
    timeout-minutes: 20
    steps:
      - name: Pull repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            thirdeye-ui
      - name: Set git ci user info
        run: |
          git config --global user.email "thirdeye-ci@startree.ai"
          git config --global user.name "ThirdEye CI"
      - name: Install node and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: './thirdeye-ui/package-lock.json'
      - name: Release UI
        run: |
          cd thirdeye-ui
          npm ci
          npm run build
          export GH_SHA=$(git log -1 --format="%H")
          npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.UI_SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Slack - Notify Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "ThirdEye frontend release succeeded."
          SLACK_TITLE: SUCCESS
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack - Notify Failure
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "@here - ThirdEye frontend release failed."
          SLACK_TITLE: FAILURE
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
