name: License header check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  header-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          # don't enable cache - or ensure header check and distribution tests have different cache keys
          java-version: '11'
          distribution: 'adopt'
      - name: check
        run: ./mvnw -T 1C -B clean license:check
